[package]
name = "geo-mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = "0.5"
maxminddb = "0.27.1"
serde_json = "1"
sha2 = "0.10"
ureq = { version = "2", default-features = true }
geo-rules = { path = "../geo-rules" }
